// Top packages by download count, used for typosquatting detection.
// If an install target has Levenshtein distance 1-2 from any entry here,
// it is flagged as a potential typosquat.

export const POPULAR_PIP: readonly string[] = [
  "requests", "boto3", "urllib3", "botocore", "setuptools", "pip",
  "s3transfer", "python-dateutil", "six", "certifi", "idna",
  "charset-normalizer", "packaging", "typing-extensions", "colorama",
  "pyyaml", "cryptography", "cffi", "numpy", "pandas", "scipy",
  "matplotlib", "pillow", "flask", "django", "fastapi", "sqlalchemy",
  "aiohttp", "httpx", "pydantic", "click", "rich", "typer",
  "pytest", "black", "mypy", "pylint", "flake8", "ruff", "isort",
  "coverage", "tqdm", "loguru", "structlog", "celery", "redis",
  "psycopg2", "pymongo", "motor", "alembic", "passlib", "bcrypt",
  "pyjwt", "authlib", "paramiko", "fabric", "ansible", "awscli",
  "google-cloud-storage", "azure-storage-blob", "openai", "anthropic",
  "langchain", "transformers", "torch", "tensorflow", "scikit-learn",
  "xgboost", "lightgbm", "plotly", "seaborn", "jupyter", "ipython",
  "arrow", "pendulum", "pytz", "humanize", "attrs", "cattrs",
  "marshmallow", "simplejson", "orjson", "ujson", "msgpack",
  "protobuf", "grpcio", "websockets", "starlette", "uvicorn",
  "gunicorn", "werkzeug", "jinja2", "markupsafe", "itsdangerous",
  "wtforms", "sqlmodel", "tortoise-orm", "peewee", "pymysql",
  "asyncpg", "aiosqlite", "tenacity", "cachetools", "diskcache",
  "joblib", "dask", "ray", "apscheduler", "schedule", "psutil",
  "docker", "kubernetes", "invoke", "nox", "tox", "hypothesis",
  "faker", "factory-boy", "responses", "moto", "sentry-sdk",
  "datadog", "prometheus-client", "opentelemetry-api", "pynacl",
  "pyotp", "qrcode", "opencv-python", "pytesseract", "pdfminer",
  "pypdf2", "reportlab", "openpyxl", "xlrd", "python-docx", "lxml",
  "beautifulsoup4", "scrapy", "selenium", "playwright", "httplib2",
  "pycurl", "pycryptodome", "parameterized", "mock",
];

export const POPULAR_NPM: readonly string[] = [
  "lodash", "chalk", "commander", "debug", "moment", "axios",
  "express", "react", "react-dom", "vue", "typescript", "webpack",
  "babel-core", "eslint", "prettier", "jest", "mocha", "chai",
  "sinon", "supertest", "nodemon", "dotenv", "cors", "helmet",
  "morgan", "body-parser", "cookie-parser", "express-session",
  "passport", "jsonwebtoken", "bcrypt", "crypto-js", "uuid",
  "date-fns", "dayjs", "luxon", "ramda", "underscore", "async",
  "bluebird", "rxjs", "mobx", "redux", "zustand", "recoil",
  "next", "nuxt", "gatsby", "vite", "rollup", "esbuild", "parcel",
  "postcss", "tailwindcss", "sass", "less", "styled-components",
  "emotion", "socket.io", "ws", "mongoose", "sequelize", "typeorm",
  "prisma", "knex", "mysql2", "pg", "redis", "ioredis", "mongodb",
  "graphql", "apollo-server", "apollo-client", "grpc", "protobufjs",
  "joi", "yup", "zod", "sharp", "jimp", "multer", "formidable",
  "busboy", "nodemailer", "stripe", "aws-sdk", "firebase",
  "docker-modem", "tar", "archiver", "unzipper", "glob",
  "minimatch", "micromatch", "chokidar", "fs-extra", "mkdirp",
  "rimraf", "cross-env", "concurrently", "npm-run-all", "husky",
  "lint-staged", "commitlint", "yargs", "minimist", "meow",
  "inquirer", "prompts", "ora", "listr2", "boxen", "table",
  "cli-table3", "figlet", "winston", "bunyan", "pino", "loglevel",
  "log4js", "sentry", "source-map", "autocannon", "artillery",
  "superagent", "got", "node-fetch", "undici", "cheerio",
  "puppeteer", "playwright", "cypress", "nightwatch", "webdriverio",
  "selenium-webdriver", "jsdom", "enzyme", "storybook",
  "event-source-polyfill", "ua-parser-js", "node-ipc",
  "simple-get", "babel-cli", "d3", "electron", "mongoose",
  "socket.io-client", "mysql", "cross-env", "lodash-es",
];
